name: gh-pages

on: [push, pull_request]

jobs:
  deploy:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest ]
        node: [ 20 ]

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: npm
          cache-dependency-path: "./package-lock.json"
      - run: npm install
      - run: npm run generate
      - uses: actions/deploy-pages@v4
        with:
          BRANCH: gh-pages
          FOLDER: '.output/public'
          CLEAN: true
